[package]
name = "viewkai-engine"
version = "0.0.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "PDFium rendering engine for viewkai"

[dependencies]
viewkai-core = { path = "../viewkai-core" }
pdfium-render = { workspace = true, features = ["pdfium_latest", "image_latest"] }

[dev-dependencies]
serde_json = { workspace = true }
