[package]
name = "viewkai-demo"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Demo app for viewkai — native + WASM"

[[bin]]
name = "viewkai-demo"
path = "src/main.rs"

[dependencies]
viewkai = { path = "../viewkai" }
eframe = { workspace = true }
rfd = { workspace = true }
ehttp = { workspace = true }
