[package]
name = "viewkai"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Rust PDF viewer library targeting wasm32 and native, built on pdfium-render and egui"

[dependencies]
viewkai-core = { path = "../viewkai-core" }
viewkai-engine = { path = "../viewkai-engine" }
egui = { workspace = true }
