[package]
name = "viewkai-app"
version = "0.2.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Native PDF viewer application built on viewkai"
readme = "../../README.md"
keywords = ["pdf", "egui", "viewer", "native"]
categories = ["gui", "rendering"]

[[bin]]
name = "viewkai-app"
path = "src/main.rs"

[dependencies]
eframe = { workspace = true }
viewkai = { path = "../viewkai" , version = "0.2.1" }
viewkai-core = { path = "../viewkai-core" , version = "0.2.1" }
viewkai-engine = { path = "../viewkai-engine" , version = "0.2.1" }
rfd = { workspace = true }
ehttp = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

[dev-dependencies]
egui_kittest = { version = "0.34", features = ["wgpu", "snapshot", "eframe"] }

[lints]
workspace = true
